// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiSzbJjULTd6dDMnk1RPA2we1_1gclAPc',
    appId: '1:448729098612:web:6692c5a85861df9f01e421',
    messagingSenderId: '448729098612',
    projectId: 'lmhezq2u3og1a9fif4vfxxhpmdp6e1',
    authDomain: 'lmhezq2u3og1a9fif4vfxxhpmdp6e1.firebaseapp.com',
    storageBucket: 'lmhezq2u3og1a9fif4vfxxhpmdp6e1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnGIJtuNvqsQTuUWHlLPk8S36iKmjwG9Q',
    appId: '1:448729098612:android:9b9abd9bac56eff501e421',
    messagingSenderId: '448729098612',
    projectId: 'lmhezq2u3og1a9fif4vfxxhpmdp6e1',
    storageBucket: 'lmhezq2u3og1a9fif4vfxxhpmdp6e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJNBQnENepLRLRth6GQT-aBCdQopIbamI',
    appId: '1:448729098612:ios:f192418e2fcf533f01e421',
    messagingSenderId: '448729098612',
    projectId: 'lmhezq2u3og1a9fif4vfxxhpmdp6e1',
    storageBucket: 'lmhezq2u3og1a9fif4vfxxhpmdp6e1.firebasestorage.app',
    iosBundleId: 'com.divelog.app',
  );

}