// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaL_AsYzNYWan58pdeofpqIrkYXIYw4IU',
    appId: '1:989282375030:web:a6e0e450b94673b3ce9657',
    messagingSenderId: '989282375030',
    projectId: 'divedatapro',
    authDomain: 'divedatapro.firebaseapp.com',
    storageBucket: 'divedatapro.firebasestorage.app',
    measurementId: 'G-J9TV4ZCBDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGK6V6dI8v1ezFtXRYZ3xeUWrJgfGHFHI',
    appId: '1:989282375030:android:a509cfb50e4b1c92ce9657',
    messagingSenderId: '989282375030',
    projectId: 'divedatapro',
    storageBucket: 'divedatapro.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGriUHqxg6HZUeRWyULVd9HtKZ559gd2A',
    appId: '1:989282375030:ios:f59b87bad6ccb505ce9657',
    messagingSenderId: '989282375030',
    projectId: 'divedatapro',
    storageBucket: 'divedatapro.firebasestorage.app',
    iosBundleId: 'com.flnglobalgroup.divedatapro.app',
  );
}
